name: Unit tests and linting
description: Run unit tests in different python environments
inputs:
  python-version:
    required: true
    description: "Python version to run the tests"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Dev Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
      shell: bash

    - name: Run linting
      # Run tox using the version of Python in `PATH`
      run: tox -e lint
      shell: bash

    - name: Should run doc build
      run: |
        import os
        from packaging.version import Version
        with open(os.getenv("GITHUB_ENV"), "a") as file_env:
          python_version = Version("${{ inputs.python-version }}")
          min_python_version = Version("3.10")
          if python_version < min_python_version:
            file_env.write(f"DO_DOC_BUILD=false\n")
          else:
            file_env.write(f"DO_DOC_BUILD=true\n")
      shell: python
    - name: Run doc build
      # Run tox using the version of Python in `PATH`
      if: ${{ env.DO_DOC_BUILD == 'true' }}
      run: tox -e docs
      shell: bash

    - name: Run pip-audit command through GHA
      # Check dependencies for security vulnerabilities.
      # Only run on a single python version (the one that does doc builds)
      if: ${{ env.DO_DOC_BUILD == 'true' }}
      uses: pypa/gh-action-pip-audit@v1.0.8
      with:
        inputs: |
          requirements/base.txt
          requirements/dev.txt
          requirements/docs.txt
          requirements/test.txt
          requirements/vis.txt

    - name: Run unit tests
      # Run tox using the version of Python in `PATH`
      run: tox -e unit
      shell: bash