name: Create docs
description: Create Sphinx documentation and deploy it to github pages
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
      shell: bash

    - name: Deploy Sphinx docs
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs/source/
        pyproject_extras: docs