name: Cellarium CAS Repository Update Workflow
on: [push, workflow_dispatch]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.7', '3.8', '3.9', '3.10' ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/unit-tests
        with:
          python-version: ${{ matrix.python-version }}
  docs:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/docs