name: Cellarium CAS Repository Update Workflow
on: [push, workflow_dispatch]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.7', '3.8', '3.9', '3.10' ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/unit-tests
        env:
          TEST_API_TOKEN: ${{ secrets.TEST_API_TOKEN }}
          TEST_API_URL: ${{ secrets.TEST_API_URL }}
        with:
          python-version: ${{ matrix.python-version }}
